package models.network;

public enum MessageType {
		CREATE_USER, LOGIN, LOGOUT, CREATE_GROUP, INVITE_USER, JOIN_GROUP,
		CHAT_MESSAGE, LEAVE_GROUP, REMOVE_USER, DISBAND_GROUP, STATUS_RESPONSE,
		GAMEPLAY;
}
